export const TRANSACTIONS_POPULATED = 'transactions/TRANSACTIONS_POPULATED'
export const ACCOUNTS_POPULATED = 'transactions/ACCOUNTS_POPULATED'
export const CATEGORIES_POPULATED = 'transactions/CATEGORIES_POPULATED'
