export const TRANSACTIONS_POPULATED = 'transactions/TRANSACTIONS_POPULATED'
export const ACCOUNTS_POPULATED = 'transactions/ACCOUNTS_POPULATED'
export const CATEGORIES_POPULATED = 'transactions/CATEGORIES_POPULATED'

export const ACCOUNT_FILTER_UPDATED = 'ui/ACCOUNT_FILTER_UPDATED'
export const CATEGORIES_FILTER_UPDATED = 'ui/CATEGORIES_FILTER_UPDATED'
export const DATE_FILTER_UPDATED = 'ui/DATE_FILTER_UPDATED'
export const RESET_FILTER = 'ui/RESET_FILTER'
